name = "portal"
compatibility_date = "2024-10-18"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "shortener"
id = "11d3aaf4b4bf4a8bae0afd87cbd162bc"